apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/massive-house-344607/testnode # change this with your docker repository address
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: DB_SCHEMA
            value: postgres
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: "12345"
          - name: DB_HOST
            value: 10.8.11.148
          - name: DB_DATABASE
            value: bank
          - name: POSTGRES_PORT
            value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000