apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrestest
  template:
    metadata:
      labels:
        app: postgrestest
    spec:
      containers:
      - name: postgrestest
        image: postgres:alpine
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgrestest
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432